### ISSUE TITLE
4.0 does not reconnect to logstash

### ISSUE THREAD

**Issue by dimas** [logstash/logstash-logback-encoder#76] opened 2015-02-09 14:44 UTC
After we upgraded from 3.x to 4.0 we noticed that logstash started logging significantly less than it used to. After some preliminary investigation it looks like logstash appender now has troubles reconnecting to the logstash.
I cannot reproduce it with a local test (when I kill the server socket, it causes appender to reconnect in 30 sec) but in AWS environment where ELBs are used to load-balance connections to multiple logstash servers - it happens all the time.

Important observation is that there are sockets stuck in CLOSE_WAIT state on the client machine - that is socket that OS believes is already closed by server but client application (logstash appender) has not called close() on that socket yet.

```
$ sudo netstat -npt | grep 4560
tcp6       0      0 10.0.66.247:38380       10.0.140.204:4560       ESTABLISHED 1056/java       
tcp6       1      0 10.0.66.247:33733       10.0.154.223:4560       CLOSE_WAIT  1086/java       
tcp6       0      0 10.0.66.247:33735       10.0.154.223:4560       ESTABLISHED 1019/java       
tcp6       1      0 10.0.66.247:55303       10.0.160.250:4560       CLOSE_WAIT  1027/java       
tcp6       1      0 10.0.66.247:38382       10.0.140.204:4560       CLOSE_WAIT  1039/java       
tcp6       1      0 10.0.66.247:55306       10.0.160.250:4560       CLOSE_WAIT  1124/java       
tcp6       1      0 10.0.66.247:38386       10.0.140.204:4560       CLOSE_WAIT  1099/java 
```
We have 7 separate Java processes on that box and as you can see, 2 of them managed to connect (ESTABLISHED) while other 5 - failed (CLOSE_WAIT).
Problem is that these will never try to reconnect because (my assumption), the appender code did not detect the problem.

**Comment by dimas** [comment] 2015-02-09 15:13
Okay, I just confirmed I can reproduce it easily by just restarting logstash server (which is behind ELB but I am not sure it plays any role in the experiment). So all the ESTABLISHED sockets turn to CLOSE_WAIT and hang in that state forever - it never reconnects.

Just looking at AbstractLogstashTcpSocketAppender.java openSocket() I think there are a couple of a logic errors in there.
1. It catches IOException only but it should close already opened socket in case of _any_ exception.
2. one of the condition for the while loop is socket being null. But what happens if socket is assigned but then connect() fails with something like NPE? or InvalidArgumentException? it will abort the method but this.socket is already assigned so even if this method will ever be invoked again - it will just return immediatelly because this.socket != null

I would rather made socket a local variable and only assign this.socket before returning successfully. (Still need to make sure that if we are leaving method in case of _any_ exception, that locally created socket is released.

I am not sure yet if it is what causes the issue - just observations from the code...

**Comment by dimas** [comment] 2015-02-09 15:29
Than what are the IOExceptions that onEvent() catches but does not reconnect? I cannot think of anything of any conditions where client gets IOException and it does not mean at the same time that connection went wrong and must be killed...

**Comment by dimas** [comment] 2015-02-09 15:33
In addition to two logic errors above - what if socket is constructed successfully but then outputStream construction fails or even more realistically, encoder.init(outputStream) throws something?

The appender will be left in half-initialised state when some of the code believes it is all good (socket != null etc) but at the same time any attempt to use it will throw something.

**Comment by philsttr** [comment] 2015-02-09 17:35
Hi @dimas,

I'll take a look at this later tonight.  I'm running pretty much the exact same setup.

I agree that all exceptions should be caught and handled (not just IOExceptions).  Can you confirm that this is what is actually happening in your case?  What RuntimeException is being thrown? It would give me much more confidence that it will fix your problem if you can confirm it.

Note that the socket reference is set back to null in the `closeSocket` method.  So, if an IOException was thrown, the loop would continue rather than exiting.  However, obviously this is only true for IOExceptions.

I didn't handle RuntimeExceptions because those are generally from programmer error, rather than environmental problems, and likely won't be resolved by just re-iterating.  However, I'll still make the change so that the logic is extra-safe.

Phil

**Comment by dimas** [comment] 2015-02-09 17:40
To be honest, I do not know how to get that internal logging from Logback (the stuff that is sent via addWarn for example). I tried adding debug="true" to the logback.xml configuration XML but it did not help. Because of that I do not know what the actual exception is.

**Comment by philsttr** [comment] 2015-02-09 17:53
Hmm,  can you try adding a [OnConsoleStatusListener](http://logback.qos.ch/manual/configuration.html#statusListener) and looking at the stdout of your process?

```
<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />
```

**Comment by dimas** [comment] 2015-02-09 18:31
Does not display any exceptions at all.
Right now I killed the last logstash instance behind ELB and the way it is now is that ELB accepts the connection but immediatelly closes it. 

```
$ nc -v mylogstashserver 4560
Connection to mylogstashserver 4560 port [tcp/*] succeeded!
$
```

so nc instantly returns to command line (while normally it should hang waiting for the input). And in that state my cosole says

```
18:26:08,817 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash] - Log destination mylogstashserver:4560: connection established.
```

but it never says it lost the connection.
I am not sure at the moment how to reproduce this behaviour with some (other than ELB itself) tools but it should be possible with nc as well. So I will experiment with it more tomorrow but for now it looks like logback appender does not detect connection closure when it happens immediately.

**Comment by dimas** [comment] 2015-02-09 18:33
(I mean it should be possible to simulate server-side that accepts and drops connections with just NC or something similar)

**Comment by philsttr** [comment] 2015-02-09 20:38
To attempt to reproduce this, I have a load balancer with no handlers behind it.  I believe the load balancer has the same behavior as yours, in that it initially accepts the connection, but then immediately closes it.  I have verified this through wireshare.  When connecting, I see:

```
-> SYN           
<- SYN, ACK
-> ACK
<- FIN, ACK
-> ACK
```

Then, when attempting to write the first event to the socket outputstream, I see the following:

```
-> PSH, ACK
<- RST
```


To my surprise, no exception is thrown by java's socket output stream here.  So, the appender thinks the event was written successfully.  I'm guessing the output stream write returns before the RST reply is received.

However, when writing the NEXT event, the following exception is thrown:

```
12:18:54,798 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[centralized] - Log destination xxx:yyyy: unable to send event: Software caused connection abort: socket write error java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketException: Software caused connection abort: socket write error
        at      at java.net.SocketOutputStream.socketWrite0(Native Method)
        at      at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
        at      at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
        at      at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at      at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at      at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onEvent(AbstractLogstashTcpSocketAppender.java:200)
        at      at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onEvent(AbstractLogstashTcpSocketAppender.java:163)
        at      at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at      at java.lang.Thread.run(Thread.java:745)
```

Since this is a `SocketException`, the connection is reestablished (and reclosed by the LB), and the cycle repeats itself.

Note that I have `immediateFlush` turned off on my encoder, so the outputstream is only flushed by the appender at the end of the batch.

I'm not sure why you do not see this same `SocketException` when attempting to write the event after the connection has been closed by the server.  I'm not sure how much I'm going to be able to debug this further, but I'll still keep investigating.

**Comment by dimas** [comment] 2015-02-09 21:47
Maybe I rushed a bit with my report. We saw the issue in live system so as soon as I saw the same symptoms in my test environment, I filled in details. But the test environment may have zero logging activities so after ELB killed the connections (for being idle for more than 1 minute), your client never restored that connection because there is no events to log and connection is only restored when these events arrive.
So experiment was not ideal to say the least. However it started because, as I said, we had the issue with live system. So now I need to figure out how to reproduce it.

However, you can see yourself that there is an issue with ELB and applications that only occasionally log something. The default AWS ELB timeout is 1 minute which you can only extend to 10 minutes. After that time, Amazon kills the connection but client won't detect it until it tries to write something into that socket. And  as you saw yourself, the first write will be lost anyway. Which means if application logs single message every 20 seconds - it is doomed to not log anything at all.
We know about that case and even wanted to add a patch that makes appender to write a single newline character into the socket every 30 seconds (configurable). However after the switch to LMAX disruptor - I have no idea how to handle it now. My idea for the patch only valid for blocking queue approach.

Again, while the problem above is very real, it is not what happened to our live system. Logging traffic there was quite substantional and yet, a socket was stuck in close_wait state forever.

**Comment by philsttr** [comment] 2015-02-09 22:02
Gotcha.  I'll treat these as two separate issues then.

1) Infrequent logging - Add keep alive functionality.  This should be simple to do regardless of queuing mechanism.  With the current implementation, the `TcpSendingEventHandler` can be modified to start up a keep alive thread in the `onStartup` method.  This thread would send newlines every X seconds to the socket if no events have been processed in the past X seconds.

2) Frequent logging, but sockets are stuck in CLOSE_WAIT state.  I haven't been able to reproduce this.  I'll keep digging, but I'll probably need your help to further diagnose this issue.

**Comment by dimas** [comment] 2015-02-10 14:04
Sure, these are two separate issues.

#1 - I doubt it will be that easy as you think. I am not sure if OutputStreams are thread safe and I doubt it. And both, disruptor onEvent thread as well as your connection keepalive thread will have to deal with socket opening/closing and writing to it... Can turn into a nightmare.
With the blocking queue it was much easier - just do time-restricted take() and if it returned because of the timeout - send a newline. Everything is within the same thread. Anyways, if you know how to fix it - it would be great.

#2 - I reproduced it and took packet dumps. Apparently it is an Amazon issue so I raised case with them. I doubt they can fix it though.
If you are curious and want to see the same issue - there is a small window between the moment you killed your server process and the moment ELB will start dropping incoming connections. If during that window you connect to it - ELB will be happily consuming all your data even there is no way to forward it to the backend server which is down. (So in tcpdump you will see it ACKs all the chunks of data you are sending)
According to Amazon support, they are buffering all the data and will send it to the backend when new connection is established. Unfortunately there will be no new connection as client does not know something is wrong with the existing one.

**Comment by philsttr** [comment] 2015-02-10 18:01
For #1, I was thinking the keep alive thread would post an event onto the RingBuffer, and therefore the event handler would send the keep alive.  There are some details to work out, but it should work.

For #2, I don't think there's anything elegant that the tcp appender can do about this case.  Periodic reconnects? Do you have any other ideas?

**Comment by dimas** [comment] 2015-02-10 18:28
1) Well, you will need to somehow understand that it is a special kind of event that does not need to be pushed through encoder. But if you can do it, then yes - this approach is probably right.
I assume I do not need to create another issue for that, right?

2) No, I cannot think of anything. It is definitely not logstash-logback-encoder's fault but Amazon's. I will keep talking to them re that case and will let you know if there are any updates.

Having said that, I think that there is a still room for improvement in TCP appender connection handling logic :)
Namely the issues I outlined in the very beginning. Even though these did not play any role in this particular problem, it still feels like it makes sense to close them just to be safe. I will summarise them here:

A) this.socket + this.outputStream are assigned before their initialisation has finished successfully so they can be used later in half-baked state.
B) openSocket() only closes opened socket in case of IOException while it should close it when leaving method because of any reason except for success.
C) I am not sure why you treating IOException differently from SockerException in onEvent - what kind of IOException may occur that does not require reconnection?

So if you agree with these, I would suggest keeping this issue open. If not - feel free to close it.

Personally I would probably do something along the lines of good old C-like stuff:
```
Socket socket = null;
OutputStream outputStream = null;
try {
  // create socket, create stream, init encoder
  succsss = true;
} finally {
  if (!success) {
    // close everything
  }

  this.socket = socket;
  this.outputStream = outputStream;
} 
```

**Comment by philsttr** [comment] 2015-02-10 18:46
Ya, I'll make all the improvements you suggest.

For #C, IOExceptions can be thrown at layers higher than the socket.  For example, if your encoder had an OutputStream that threw an IOException before even writing to the socket.
Reconnecting the socket will not help in this case.  When there is a problem with the socket, a SocketException will be thrown.

Having said that, I'll change it to reconnect on any IOException, just to be safe.  Worst case, it reattempt's connection when it's not necessary.  But that shouldn't cause too much harm.

**Comment by dimas** [comment] 2015-02-10 19:01
Well, the problem is that if SocketOutputStream throws an exception - you do not really know if it happened before touching the socket or during it. So you do now know if it can recover from it.

Anyway, thanks a lot for your work.

**Comment by philsttr** [comment] 2015-02-13 05:30
All changes suggested here have been committed to master for version 4.2.

I've done some testing here, but if you get a chance, I'd appreciate if you could let me know if they work for you.

**Closed by philsttr** 2015-02-13 05:30 UTC

**Comment by sihil** [comment] 2015-02-13 15:20
This has been causing us issues too and am glad to have found this issue. We'd be happy to try this out - is there a snapshots repo or version available that we can try?

When are you likely to push 4.2?

**Comment by dimas** [comment] 2015-02-13 18:23
@philsttr - I manually verified that it sends keepalive newline and it seem to make ELB happy so it does not kill the connection. I cannot really verify other changes properly.
We will push it to live as soon as you release 4.2

Re the original issue, there are no updates from Amazon support except that they managed to reproduce the problem and relayed it to their development team.

**Comment by philsttr** [comment] 2015-02-18 01:51
4.2 has been released.

Thanks for verifying the changes.  And good to know that Amazon is looking into the problem that you discovered.
