### ISSUE TITLE
Marker chains partialy outputed on console appender

### ISSUE THREAD

**Issue by Mumeii** [logstash/logstash-logback-encoder#340] opened 2019-06-12 23:58 UTC
Hi

I've noticed that using `%marker` within the pattern of a `ch.qos.logback.core.ConsoleAppender` only output the first marker of a chain built thanks to `.and` method.

Here is the Intellij project I've set-up in order to reproduce this trouble :

[markersPbmSandbox.zip](https://github.com/logstash/logstash-logback-encoder/files/3283539/markersPbmSandbox.zip)

Is it a bug or am I missing something here ?

**Comment by philsttr** [comment] 2019-06-13 01:02
Looks like a bug caused by the fact that the same classes in logstash-logback-encoder are used for Markers _and_ StructuredArguments.   E.g. `SingleFieldAppendingMarker` is both a `Marker` and a `StructuredArgument`

Logback's [`MarkerConverter` calls `marker.toString()`](https://github.com/qos-ch/logback/blob/8fccc8879641be6c4ad7da0f2a6057f6bb9fbd47/logback-classic/src/main/java/ch/qos/logback/classic/pattern/MarkerConverter.java#L34) when rendering the `%marker` string.

The [`SingleFieldAppendingMarker.toString()` implementation](https://github.com/logstash/logstash-logback-encoder/blob/1cabdda7c680b2f4d92a44de30ebdccabc0d5bfa/src/main/java/net/logstash/logback/marker/SingleFieldAppendingMarker.java#L100-L118) was written from a `StructuredArguments` point of view (which don't have chained references), so it only outputs itself, without the rest of the chain.

The fix would be to also output the chained markers.

The next question is how would you expect the chained markers to be joined together?

Slf4j's BasicMarker uses the format `initialMarker [subMarker1, submarker2]`  (See [here](https://github.com/qos-ch/slf4j/blob/d3f50a9185266cf03a0c1a93c15cffcd4bc32c1e/slf4j-api/src/main/java/org/slf4j/helpers/BasicMarker.java#L157-L166))  I'm not a huge fan of that though.  I'm tempted to just join them with commas or spaces.  Your thoughts?

**Comment by Mumeii** [comment] 2019-06-13 07:50
I also don't like this format as, from a chaining point of view, I don't see the point to have a special display treatment for the first marker in the chain.

I'd prefer either `[ key1=value1, key2=value2 ]` or `key1=value1, key2=value2`

As I don't know your bug fix / versionning policy, in which version could this fix be delivered ?

I'm definitly not in a hurry as I can use the `appendEntries( Map.of` workaround in the mean time, but I'm more concerned about the versionning part, as we're using the 6.0 version and I can't tell if you'll produce a minor version for that fix or you'll wait for the next major version ;)

**Comment by philsttr** [comment] 2019-06-13 21:14
I think this can be fixed in 6.1.  Should be able to get to it soon.

I'm going to go with `, ` (comma then space) as the separator.  It would be difficult to add a prefix and suffix due to the recursive nature of markers.  If you really want the prefix and suffix, you could use `[%marker]` in your pattern

**Comment by Mumeii** [comment] 2019-06-14 07:28
Perfect !

Looking forward for this 6.1 version.

And by the way thank you for this lib !

**Closed** 2019-06-15 18:11 UTC
Labels: bug
