### ISSUE TITLE
Double nested message

### ISSUE THREAD

**Issue by phillro** [logstash/logstash-logback-encoder#93] opened 2015-05-10 20:00 UTC
Using logstash logback encoder, my log messages are double nested.

Log configuration: 
https://gist.github.com/phillro/79054a245aa167cc52e3

Sample log message:
https://gist.github.com/phillro/327d4af0371828a16703

**Comment by philsttr** [comment] 2015-05-11 18:18
Can you post your logstash configuration?

Are you using the [`json_lines`](http://logstash.net/docs/1.4.2/codecs/json_lines) codec

**Comment by philsttr** [comment] 2015-05-18 01:24
Closing this issue.  I believe this was caused by not using the `json_lines` codec on logstash's side.  Please reopen if you are using the `json_lines` codec and still getting doubl nested events.

**Closed by philsttr** 2015-05-18 01:24 UTC
