### ISSUE TITLE
v4.2 with SSL is not pushing events continously

### ISSUE THREAD

**Issue by pricefx** [logstash/logstash-logback-encoder#87] opened 2015-03-09 07:38 UTC
Hi, 
we're trying to send our log events via an encrypted channel. The setup per se seems allright as events come accross occasionally, but not as real-time as with plain TCP.
So the behaviour after a while is this:
You generate log events. Nothing appears in ES (or also in the receiving logstash stdout). When we bounce the receiving logstash service, most of the time a whole bunch of old messages comes in. So the broken connection fixes it temporarily, but obviously this isn't a permanent solution.

The setup:

  	<appender name="LOGSTASH_ERROR" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
	    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
	        <level>ERROR</level>
	    </filter>  	
    	<remoteHost>${logstash-server}</remoteHost>
      	<port>5000</port>
      	<encoder class="net.logstash.logback.encoder.LogstashEncoder">
			<Pattern>
				%d{HH:mm:ss.SSS} %X{cluster} %X{req.requestURI} %X{batchsize} %X{username} - %msg%n
			</Pattern>
		</encoder>
		
		<ssl>
		    <trustStore>
		        <location>classpath:pricefx-logstash.jks</location>
		        <password>pricefx</password>
		    </trustStore>
		</ssl>	
  	</appender> 

The receiving end:

    input {
      tcp {
    port => 5000
    codec => json
    type => "logs"
    ssl_cert => "/etc/logstash/tls/logstash.crt"
    ssl_key => "/etc/logstash/tls/logstash.key"
    ssl_enable => true
    data_timeout => 300
      }
    }

I played already with a few config options, but due to the lack of a clear error message I am a bit stuck. Happy to provide logs or debug dumps or so if needed.

Cheers
Chris

**Comment by philsttr** [comment] 2015-03-10 04:53
Hi Chris,

I'm investigating this, but in the meantime.....

Can you try adding this to your logback config (inside the `configuration` element) to get more output from the appender on stdout?...

```xml
<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />
```

Also, for debugging, lower the `droppedWarnFrequency` for the appender (inside the `appender` element) to get more frequent status notifications (via that listener) for dropped events.  This will let us know if the tcp channel is just backing up, causing events to be dropped.

```xml
<droppedWarnFrequency>5</droppedWarnFrequency>
```

(Do not run with a low `droppedWarnFrequency` in production normally, because writing status messages can cause a lot of contention within logback)


As a side-note, I noticed that your configuration for `LogstashEncoder` is not correct.  The pattern that you have configured will be ignored, since `LogstashEncoder` does not have a pattern field.  You should see an error from logback on startup for this.  See the readme for how to configure `LogstashEncoder`.  If you want to use a pattern, you should use a [composite encoder](https://github.com/logstash/logstash-logback-encoder#composite-encoderlayout) with the [pattern provider](https://github.com/logstash/logstash-logback-encoder#pattern-json-provider)

**Comment by philsttr** [comment] 2015-03-10 05:21
To help with debugging, you can also take logstash out of the equation by just opening a server socket with openssl like this:

```
openssl s_server -accept 5000 -key /etc/logstash/tls/logstash.key -cert /etc/logstash/tls/logstash.crt
```

**Comment by pricefx** [comment] 2015-03-10 07:46
OK. I'll let it run with these settings (with logstash backend in the first run for now).
I removed the pattern config. Was just there as a copy'n'paste thing really.
I'll report back once I have results

**Comment by pricefx** [comment] 2015-03-10 08:20
So first results:
With the changed logback.xml I do not see any "bad" messages. It looks all as it should to my eyes:

    07:54:50,037 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - SSL protocol 'SSL' provider 'SunJSSE version 1.8'
    07:54:50,042 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - trust store of type 'JKS' provider 'SUN version 1.8': classpath:pricefx-logstash.jks
    07:54:50,043 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - trust manager algorithm 'PKIX' provider 'SunJSSE version 1.8'
    07:54:50,044 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - secure random algorithm 'SHA1PRNG' provider 'SUN version 1.8'
    07:55:05,722 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [net.logstash.logback.appender.LogstashTcpSocketAppender]

--snip--

    07:55:06,001 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination <server>:5000: connection established.
    07:55:06,001 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH_ERROR] - Log destination <server>:5000: connection established.

Further on, I do not see anything related to dropped events or the like.
However when playing with it I made an observation that may lead to something:
- I started the application with a logstash backend
- Then while running, I stopped logstash and replaced it with the openssl server you mentioned
- I triggered some events -> Nothing appearing in the stdout of openssl server
- I stopped openssl and started logstash again
- The events I was waiting for, now appeared in logstash !

=> This means to me that they were not sent yet. A side note: We are not pushing loads of events. Maybe 1 per second in average, and there may be long pauses in between with no event at all. Would that have an impact? Like a message sending buffer that is just too big for our use case? Haven't found anything in that direction though...

Cheers
Chris

**Comment by philsttr** [comment] 2015-03-10 19:45
Depending on the timing of your steps, the latest behavior you observed might just be caused by the fact that the reconnection delay is 30 seconds by default.  When the appender first notices a broken socket, it will attempt reconnection immediately.  If that fails, it will retry connecting after the reconnection delay (and continue polling).

The tcp appender may have never attempted to connect to the openssl server.  Try lowering the reconnection delay on the appender just to be sure.

```xml
<reconnectionDelay>5 seconds</reconnectionDelay>
```

I am also surprised that you did not see any broken pipe errors on stdout (logged via the `OnConsoleStatusListener`).  Do you have something sitting on your network in front of logstash that would keep the connection open?

**Comment by pricefx** [comment] 2015-03-10 19:50
I can rule that out. I was tailing both logs side by side and obviously waiting until it reconnected. The time from generating the events while openssl was the backend until I killed that and switched back to logback was in the range of 5-10 minutes to give it some time if needed.
The only thing in between is a iptables firewall around the logstash server. Nothing else really.

**Comment by philsttr** [comment] 2015-03-11 01:44
Ok.  I'm out of ideas at the moment.  The next step is either

A) instrumenting the code with a lot more debug logging

OR

B) stepping through the code with a debugger

Are you familiar with java debugging?  If so, I would really appreciate it if you could step through the code and let me know what you see.  Particularly in AbstractLogstashTcpSocketAppender on [Line 298](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L298) and [Line 307](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L307).  If neither of those lines are throwing an exception, then the appender will not detect the socket is broken and attempt to reconnect

**Comment by philsttr** [comment] 2015-03-11 03:55
For A... I've created a [debug branch](https://github.com/logstash/logstash-logback-encoder/tree/debug) that has extra status messages for:

* when an event is enqueued
* when an event is dequeud
* when an event is successfully sent
* when a keepAlive is sent.

If you want to build and use that for debugging, it will show what the code is doing better.

Note that you must have the OnConsoleStatusListener to see the extra debug messages on stdout.

**Comment by pricefx** [comment] 2015-03-11 08:08
I added the debug build to the local build (yes, I know debugging). Below is the log of the test. The CommandDisaptcher stuff generates one event per URI.

	08:53:52,543 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination es1:5000: connection established.
	08:54:04.725 [qtp1368316340-72] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/login/extended
	08:54:04,878 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:null - Payload:[{"startRow":0,"endRow":0,"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:04,878 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:null - Payload:[{"startRow":0,"endRow":0,"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:05.010 [qtp1368316340-73] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/formulamanager.getnames/DEFAULT
	08:54:05.012 [qtp1368316340-72] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/fetch/UG
	08:54:05.015 [qtp1368316340-74] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/productmanager.fetchproducts
	08:54:05.023 [qtp1368316340-81] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/fetch/UG
	08:54:05.025 [qtp1368316340-82] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/formulamanager.getnames/DEFAULT
	08:54:05,074 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{"_constructor":"AdvancedCriteria","operator":"and","criteria":[{"fieldName":"uniqueName","operator":"inSet","value":[]}]},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:05,074 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":300,"textMatchStyle":"substring","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:05,074 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{"_constructor":"AdvancedCriteria","operator":"and","criteria":[{"fieldName":"uniqueName","operator":"inSet","value":[]}]},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:05,076 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:05,076 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:05.118 [qtp1368316340-81] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/productmanager.fetchproducts
	08:54:05.119 [qtp1368316340-72] INFO  test/admin n.p.server.CommandDispatcher - Request uri: /test/fetch
	08:54:05,120 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:null - Payload:[{"startRow":0,"endRow":0,"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:54:05,120 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Enqueued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":300,"textMatchStyle":"substring","sortBy":["lastUpdateDate"],"data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:56:31,905 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination es1:5000: unable to send event: Connection reset java.net.SocketException: Connection reset
		at java.net.SocketException: Connection reset
		at 	at java.net.SocketInputStream.read(SocketInputStream.java:189)
		at 	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	--snip--
	08:56:33,057 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination es1:5000: connection failed. Waiting 28854ms before attempting reconnection. java.net.ConnectException: Connection refused: connect
		at java.net.ConnectException: Connection refused: connect
		at 	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
		at 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
		at 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
		at 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	--snip--
	08:57:01,946 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Log destination es1:5000: connection established.
	08:57:06,766 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:null - Payload:[{"startRow":0,"endRow":0,"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:06,767 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{"_constructor":"AdvancedCriteria","operator":"and","criteria":[{"fieldName":"uniqueName","operator":"inSet","value":[]}]},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:08,185 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{"_constructor":"AdvancedCriteria","operator":"and","criteria":[{"fieldName":"uniqueName","operator":"inSet","value":[]}]},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:08,186 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":300,"textMatchStyle":"substring","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:08,738 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":300,"textMatchStyle":"substring","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:08,738 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{"_constructor":"AdvancedCriteria","operator":"and","criteria":[{"fieldName":"uniqueName","operator":"inSet","value":[]}]},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:09,193 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{"_constructor":"AdvancedCriteria","operator":"and","criteria":[{"fieldName":"uniqueName","operator":"inSet","value":[]}]},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:09,194 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:09,741 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:09,741 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:11,846 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":0,"textMatchStyle":"startsWith","data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:11,847 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:null - Payload:[{"startRow":0,"endRow":0,"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:12,785 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:null - Payload:[{"startRow":0,"endRow":0,"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:12,785 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Dequeued event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":300,"textMatchStyle":"substring","sortBy":["lastUpdateDate"],"data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]
	08:57:13,337 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - Sent event [INFO] IP:127.0.0.1 Param:dataLocale=default&isc_dataFormat=json - Payload:[{"operationType":"fetch","startRow":0,"endRow":300,"textMatchStyle":"substring","sortBy":["lastUpdateDate"],"data":{},"outType":"JSON","omitNullFields":true,"distinctResults":false}]

The test was as such:
- I started the whole thing in debug (against a logstash server on es1:5000)
- I created a few events. The breakpoint in AbstractLogstashTcpSocketAppender triggered. I stepped over encoder.doEncode(logEvent.event);
- That step-over did not return. It basically blocked the thread somewhere in there: 
    
Daemon Thread [logback-async-disruptor-appender-es1:5000-1]  [Stepping]

- I bounced logstash
- The blocked thread came back and also all pending events got sent

**Comment by pricefx** [comment] 2015-03-11 09:02
Stepped into the guts of it.
Seems the blocking bit comes from here:

    outputStream.flush();

in net.logstash.logback.encoder.CompositeJsonEncoder (line 83)

**Comment by philsttr** [comment] 2015-03-12 01:15
Hmm.  That is really bizarre.   flush() should only block if the receiver is slower than the sender (therefore causing the sender's tcp send buffer to fill up).  I'm not sure why the flush would block at startup if the server (logstash) is up and reading data from the stream.

In any case, I'm not sure if there's anything the tcp appender can do in this situation.  There's no way to configure a write timeout.  And it can't use nio, since logback's [`Encoder`](http://logback.qos.ch/xref/ch/qos/logback/core/encoder/Encoder.html) interface uses `OutputStream` (i.e. not nio)

Any chance you could grab a tcpdump on both the client and server side to look at the packets going across the wire?

**Comment by pricefx** [comment] 2015-03-12 08:14
I did a network dump and that lead me to something that may be the root cause actually.
The network dump showed that when an event is sent (and gets stuck) the client sends a "ClientHello" TLS handshake message. The server ACKs that one but does not send a "Server Hello" which would be the next step.
Why?
My theory goes in that direction that in our config we actually have two tcp appenders with same port & destination. And it seems that whichever connects first goes through the handshake process (and can send events) and the second one gets stuck - presumably as the server thinks the handshake is already complete as it can't tell the clients apart. This does obviously not happen with plain tcp as there is no handshake involved. So far my theory.

So I believe the solution is that only one single appender to a given SSL port can be configured. The reason we have two is that we have one with a filter

	    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
	        <level>ERROR</level>
	    </filter> 

and the other not, as the other is linked to different loggers. So I guess either I come up with a complex filter rule (to pack it all into one appender) or I open up a second port on logstash

**Comment by philsttr** [comment] 2015-03-13 04:20
Can you try using the `json_lines` codec on the logstash side?  In #88, @piefel described similar symptoms when using the `json` codec

**Comment by pricefx** [comment] 2015-03-13 07:27
I don't think I have the same issue. I do not see parsing errors at the receiving end and the behaviour is also appearing with an openssl server at the backend

**Comment by philsttr** [comment] 2015-03-13 16:04
Ok cool, just wanted to rule it out.  I haven't had a chance to investigate your recent findings, and may not be able to for a few days.  But I plan to get to it.

**Comment by philsttr** [comment] 2015-03-14 07:28
This is really frustrating.

I have configured two appenders to connect to the same destination host/port via SSL.

When using openssl s_server on the receiving end... I have been able to reproduce what you are seeing _occasionally_.  (e.g. the appender hangs in flush) Sometimes it reproduces, sometimes it does not.  After trying about 20 times, it reproduces for me about 50% of the time. 

However, I have not been able to reproduce this when using logstash on the receiving end. 

I also noticed that sometimes my client java app would hang while generating the random seed for SecureRandom.  This is because it's waiting for bytes from /dev/random.  When I switched the java app to /dev/urandom (`-Djava.security.egd=file:/dev/./urandom`), my java app seeds instantly.

So, this got me thinking, I wonder if in your case logstash is just waiting on entropy to generate the random numbers required for the handshake.  Just a wild guess, but I'm throwing it out there.

You could try configuring logstash to start java with `-Djava.security.egd=file:/dev/./urandom` (note the extra `/./` is required)  to check if it solves the problem (assuming use of jruby)

In any case, it might be beneficial to get a stackdump of logstash on the server side when there is an appender waiting on the client side, just to see if we can see what the server side is doing.

I'm not going to be able to look further into this for a while.  I might be able to get back to it toward the end of next week, but it may be a couple weeks.

**Comment by pricefx** [comment] 2015-03-14 08:43
No problem. I really appreciate your help here.
At least you can reproduce that, which kinda makes a totally screwed up setup on my side here at least a bit unlikelier. I honestly don't know if I use a jruby logstash. I use the default Debian package from out there which runs on a default java. But I can try nevertheless

**Comment by pricefx** [comment] 2015-03-25 07:57
A quick update here after a while of running it with the two changes (individual ports for the two appenders and the urandom jvm setting): It still happens. I have the feeling that it is slightly better, but that might be coincidence or just plain wrong. But it's not away :(

**Comment by philsttr** [comment] 2015-04-06 00:57
Hi @pricefx, 

I'm back and looking into this again.  Sorry, for the delay.

I have just made a change to master (4.3-SNAPSHOT) to set the socket SO_TIMEOUT prior to connection.  This timeout only affects _reads_ from the socket, which are performed during the SSL handshake.  Now the the handshake will fail with a read timeout, rather than just hanging forever like the previous behavior.  So, at least the failure condition is slightly better.  

However, this still doesn't solve the problem of why the handshake is not completing.

Since I haven't been able to reproduce this with logstash (I've only been able to reproduce this with openssl), can you reproduce this once more with logstash, and take a stackdump of the logstash server process while messages are not being received?  This might give us some insight into why the logstash server is not completing the handshake.

To take a stackdump use `jstack <pid>` (stack will be dumped on the jstack process stdout) or `kill -SIGQUIT <pid>` (stack will be dumped on the logstash process stdout)

**Comment by pricefx** [comment] 2015-04-06 14:06
Hi,

attached some logstash stacks.
The first three were taken once I had it replicated (i.e. client was hanging in "flush") to show which stacks/threads are "moving". Approx. time delta between each is maybe 1 minute. The last one is after I restarted logstash.
Note: This logstash instance is fed by many servers, so not a "clean and clinical" debug trace here.
Stacks are here:
http://fileupload.pricefx.eu/logstash_stacks.zip

**Comment by philsttr** [comment] 2015-04-08 07:33
Some progress tonight, but still no definitive answers yet...

One thing I found out is that `openssl s_server` will only accept one connection at a time.  This is why I am able to reproduce this using openssl.  I changed my test to keep the connections open a bit longer, and I can reproduce this 100% of the time using `openssl s_server`.  I still cannot reproduce it using logstash.

I created a separate test program to get this down to bare-bones debugging.  The test program will start two threads.  Each thread will

1. connect to the same destination host/port over SSL, using a read and connection timeout of 2 seconds
2. write a message
3. sleep for 5 seconds
4. close the connection

When I execute this against an openssl s_server (started using `openssl s_server -accept 4561 -key ssl.key -cert ssl.cert -state`), the first thread connects and sends the message successfully.  The second thread times out during the ssl handshake (just like the tcp appender now that I've added an SO_TIMEOUT).

When I execute this against logstash, both messages are sent successfully.

So, perhaps you can run this against your logstash server to see if you get the same results.  Try running it locally with logstash (on the same machine), and try running it remotely (connecting through the load balancer if you have one), to see if you get different results.

Here's the test code

```java
import java.io.IOException;
import java.net.InetSocketAddress;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;


public class HandshakeTest {
    
    private static final int NUM_CONNECTIONS = 2;
    private static final int CONNECT_TIMEOUT = 2000;
    private static final int SLEEP_TIME = 5000;
    
    private static final X509TrustManager ACCEPT_ALL_TRUST_MANAGER = new X509TrustManager() {

        @Override
        public void checkClientTrusted(X509Certificate[] chain, String authType)
                throws CertificateException {
        }

        @Override
        public void checkServerTrusted(X509Certificate[] chain, String authType)
                throws CertificateException {
        }

        @Override
        public X509Certificate[] getAcceptedIssuers() {
            return null;
        }
        
    };
    
    public static void main(String[] args) throws InterruptedException {
        
        final String host = args.length >= 1 ? args[0] : "localhost"; 
        final int port = args.length >= 2 ? Integer.parseInt(args[1]) : 4561; 
        
        ExecutorService executor = Executors.newFixedThreadPool(NUM_CONNECTIONS);
        
        List<Future<Object>> futures = new ArrayList<Future<Object>>(NUM_CONNECTIONS);
        for (int i = 0; i < NUM_CONNECTIONS; i++) {
            
            final String message = "Hello World " + i + "\n";
            
            futures.add(executor.submit(new Callable<Object>() {
    
                @Override
                public Object call() throws Exception {
                    SSLSocket socket = null;
                    try {
                        
                        SSLContext context = SSLContext.getInstance("SSL");
                        context.init(null, new TrustManager[] {ACCEPT_ALL_TRUST_MANAGER}, null);
                        
                        SSLSocketFactory socketFactory = context.getSocketFactory();
                        
                        socket = (SSLSocket) socketFactory.createSocket();
                        socket.setSoTimeout(CONNECT_TIMEOUT);
                        socket.connect(new InetSocketAddress(host, port), CONNECT_TIMEOUT);
                        socket.getOutputStream().write(message.getBytes("UTF-8"));
                        socket.getOutputStream().flush();
                        System.out.println("Sent: " + message);
                        
                        Thread.sleep(SLEEP_TIME);
                        return null;
                    } finally {
                        try {
                            if (socket != null) {
                                socket.close();
                            }
                        } catch (IOException e) {
                            // ignore
                        }
                    }
                }
            }));
        }
        
        for (Future<?> future : futures) {
            try {
                future.get();
            } catch (ExecutionException e) {
                e.getCause().printStackTrace();
            }
        }
        
        executor.shutdown();
        
        executor.awaitTermination(1, TimeUnit.MINUTES);
    }
}
```

Compile it, and run it...

```
$ javac HandshakeTest.java
$ java -classpath . HandshakeTest localhost 4561
Sent: Hello World 1

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	at sun.security.ssl.InputRecord.read(InputRecord.java:480)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:702)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at java.io.OutputStream.write(OutputStream.java:75)
	at HandshakeTest$2.call(HandshakeTest.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

If successful, you'll see two "Sent" messages.   If unsuccessful, you'll see the above output.

**Comment by pricefx** [comment] 2015-04-08 13:11
Tried it just remotely. Even with NUM_CONNECTIONS=10 it seems to always work.
I can see the messages in the logstash stdout file

**Comment by pricefx** [comment] 2015-04-10 09:10
I disabled our current issue workaround (restarting logstash every hour) and reran the test after one day of not restarting it. I see that consistently, for *all* connections. Not a single one working.
After I restarted logstash service all tests worked fine again.
Interestingly only some source hosts seemed to get stuck. I saw events from a few other hosts still coming in. So my conclusion would be that this is rather a logstash problem

root@nexus.pricefx.net ~/logstash-test # java -classpath . HandshakeTest es1 5000
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:728)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        at java.io.OutputStream.write(OutputStream.java:75)
        at HandshakeTest$2.call(HandshakeTest.java:73)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by philsttr** [comment] 2015-04-11 17:20
Ok, thank you for all the help you've done investigating this on your side.  Let me know if I can help further.

Closing this issue.

**Closed by philsttr** 2015-04-11 17:20 UTC

**Comment by AniFengx** [comment] 2017-09-13 14:02
Hey.When i use your # @philsttr HandshakeTest .It report Read timed out.Does it mean the logstash has a problem not the logback?
