### ISSUE TITLE
Marker#and is not supported

### ISSUE THREAD

**Issue by gpremer** [logstash/logstash-logback-encoder#62] opened 2015-01-08 06:31 UTC
`net.logstash.logback.marker.LogstashMarker` provides an `and` method, but it is not usable because the various derived Markers do not override the `add` method defined in slf4j-api. The `add` from `org.slf4j.helpers.BasicMarker` assumes there's a list of `Marker`s, but that's not the case for the logstash markers, so `add` ends up adding extra fields to it's `referenceList`, but that list is not used when generating JSON at serialisation time.

So, either `and` should throw an `UnsupportedException` or the various `add` methods should be implemented. It does seem though that several of the logstash markers would have a difficult time implementing `add` in a consistent way.

**Comment by philsttr** [comment] 2015-01-08 07:08
Hi @gpremer,

Can you provide a unit test, or sample code that reproduces the problem you are having?  I just tried using the `and` method, and it's working for me.

I used it like this:

    LOGGER.info(append("n1", "v1").and(append("n2", "v2")), "Testing marker and logging.");


and received the following log output (formatted for clarity)...

    {
        "@timestamp":"2015-01-07T22:56:22.482-08:00",
        "message":"Testing marker add logging.",
        "logger":"net.logstash.logback.encoder.MarkerAndTest",
        "thread":"main",
        "level":"INFO",
        "levelVal":20000,
        "n1":"v1",
        "n2":"v2"
    }

It works internally like this:
* When you call `and`, it will add the marker provided as an argument (e.g. `n2`) to the `referenceList ` of the marker on which `and` is invoked (e.g. `n1`)
* Later, at logging time, when the `LogstashFormatter` writes the event, the markers are written to the json output in `LogstashFormatter.writeLogstashMarkerIfNecessary` [here](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/LogstashFormatter.java#L297).
 * The first marker (`n1`) will get written on [line 300](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/LogstashFormatter.java#L300), and
 * then the referenced markers (`n2`) are recursively written on [line 306](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/LogstashFormatter.java#L306)

**Comment by gpremer** [comment] 2015-01-08 08:53
Hum, judging your test, it seems that the problem may be related to the way we test. At the moment I'm just writing unit tests and not quite ready to seem how it looks in elasticsearch/kibana.

We've used the same way of testing as in the logstash unit tests.

```java
    @Test
    public void thatMarkerEntriesCanBeAppended() throws Exception {
        // given
        final LogstashMarker marker = Markers.appendEntries(ImmutableMap.of("k1", "v1"));

        // when
        final LogstashMarker combo = marker.and(Markers.appendEntries(ImmutableMap.of("k2", "v2")));

        // then
        final StringWriter stringWriter = new StringWriter();
        final JsonGenerator jsonGenerator = new JsonFactory().createGenerator(stringWriter);

        jsonGenerator.writeStartObject();
        combo.writeTo(jsonGenerator);
        jsonGenerator.writeEndObject();
        jsonGenerator.flush();

        assertThat(stringWriter.toString()).contains("k1");
        assertThat(stringWriter.toString()).contains("k2");
    }

    @Test
    public void thatMarkersCanBeAppended() throws Exception {
        // given
        final LogstashMarker marker = Markers.append("k1", "v1");

        // when
        final LogstashMarker combo = marker.and(Markers.append("k2", "v2"));

        // then
        final StringWriter stringWriter = new StringWriter();
        final JsonGenerator jsonGenerator = new JsonFactory().createGenerator(stringWriter);

        jsonGenerator.writeStartObject();
        combo.writeTo(jsonGenerator);
        jsonGenerator.writeEndObject();
        jsonGenerator.flush();

        assertThat(stringWriter.toString()).contains("k1");
        assertThat(stringWriter.toString()).contains("k2");
    }
```
What we get is  (twice):
```
   java.lang.AssertionError: expecting:<'{"k1":"v1"}'> to contain:<'k2'>
```

Since both of these unit tests fail, and in light of your comments, it would seem better to test using a `LogstashFormatter` instance. However, it's not clear from the API how to go about that.

The issue is not critical for us (and certainly not if it does not occur at run time) as we worked around it  appending entries to the map we supply to `appendEntries` instead of calling `appendEntries` multiple times.

**Comment by philsttr** [comment] 2015-01-08 17:57
Ok.  Yeah, I can see why your test fails, since it only calls `marker.writeTo`, which only writes *this* marker, and not its references.  It's the `LogstashFormatter` that actually does the recursive marker writes of the references.

If you really want to confirm behavior in your unit tests, you could write tests against `LogstashFormatter` similar to the [LogstashEncoderTest](https://github.com/logstash/logstash-logback-encoder/blob/master/src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java) 

I'm going to close this issue, since logstash-logback-encoder is working as expected.

**Closed by philsttr** 2015-01-08 17:57 UTC

**Comment by gpremer** [comment] 2015-01-08 18:09
That makes sense. Thanks for your support.
