### ISSUE TITLE
Using TCP Appenders with markers

### ISSUE THREAD

**Issue by ssabnis** [logstash/logstash-logback-encoder#86] opened 2015-03-04 20:13 UTC
I have a java program using the logstah encoder, I am using the FlieAppender it is working fine. I can additional fields using the Map based markers. and log lines are produced in JSON format compatible with logstash. Now I switch the logback.xml to do the TCP socket appender to send JSON log lines to SYSLOG server, I get the following error.
java.lang.TypeNotPresentException: Type ch.qos.logback.access.spi.IAccessEvent not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:84)
	at java.lang.Class.getGenericSuperclass(Class.java:696)
	at com.sun.beans.TypeResolver.prepare(TypeResolver.java:308)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:185)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:169)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:169)
	at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:81)
	at java.beans.FeatureDescriptor.getReturnType(FeatureDescriptor.java:370)
	at java.beans.PropertyDescriptor.findPropertyType(PropertyDescriptor.java:661)
	at java.beans.PropertyDescriptor.updateGenericsFor(PropertyDescriptor.java:636)
	at java.beans.Introspector.addPropertyDescriptor(Introspector.java:595)
	at java.beans.Introspector.addPropertyDescriptors(Introspector.java:604)
	at java.beans.Introspector.getTargetPropertyInfo(Introspector.java:457)
	at java.beans.Introspector.getBeanInfo(Introspector.java:418)
	at java.beans.Introspector.getBeanInfo(Introspector.java:163)
	at ch.qos.logback.core.joran.util.PropertySetter.introspect(PropertySetter.java:79)
	at ch.qos.logback.core.joran.util.PropertySetter.getMethod(PropertySetter.java:393)
	at ch.qos.logback.core.joran.util.PropertySetter.findAdderMethod(PropertySetter.java:203)
	at ch.qos.logback.core.joran.util.PropertySetter.computeAggregationType(PropertySetter.java:177)
	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.isApplicable(NestedComplexPropertyIA.java:61)
	at ch.qos.logback.core.joran.spi.Interpreter.lookupImplicitAction(Interpreter.java:237)
	at ch.qos.logback.core.joran.spi.Interpreter.getApplicableActionList(Interpreter.java:256)
	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:144)
	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:76)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:68)
	at com.arrayentinsights.connecteddevices.ArrayentStats.main(ArrayentStats.java:61)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.access.spi.IAccessEvent
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)

My logback.xml is like this

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appender name="stash" class="net.logstash.logback.appender.LogstashAccessTcpSocketAppender">
      
      <remoteHost>host</remoteHost>
      <port>10514</port>

      
      <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
  </appender>

  <appender-ref ref="stash" />
</configuration>

Any help appreciated

**Comment by philsttr** [comment] 2015-03-04 20:42
Can you try adding the logback-access jar to your classpath?

I realize it shouldn't be required.  I'll look into this when I get a chance.  But, adding it to your classpath should work around this problem in the meantime.

**Comment by ssabnis** [comment] 2015-03-04 22:30
Thanks, I added the access jar the error seems to go away, now I have the syslog configured and running, the logback seems to communicate to syslog, but I do not see the logs in syslog, is it because we are publishing in JSON style, I am using marketers to add custom fields to the log line. Any clue?

**Comment by philsttr** [comment] 2015-03-05 04:59
One possibility is that syslog might not recognize what is being sent to it.  `LogstashEncoder` just sends pure JSON, separated by newlines, by default.

Using markers would not cause this problem since syslog does not look at the fields within the JSON.

What syslog are you running? rsyslog or syslog-ng?

Something you can try is to prefix the events with syslog headers by adding the following to your encoder configuration:

```xml
    <prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
      <layout class="ch.qos.logback.classic.PatternLayout">
        <pattern>%syslogStart{USER}</pattern>
      </layout>
    </prefix>
```

**Comment by ssabnis** [comment] 2015-03-05 19:18
Thanks for your response, here is my config file. help me out this is crucial for my project. I am trying to provide the FileAppender or Syslog depending upon the a configuration in my application. Any help appreciated!

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<conversionRule conversionWord="syslogStart"
		converterClass="ch.qos.logback.classic.pattern.SyslogStartConverter" />
	<appender name="stash"
		class="net.logstash.logback.appender.LogstashTcpSocketAppender">

		
		<remoteHost>host</remoteHost>
		<port>10514</port>

		<prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
			<layout class="ch.qos.logback.classic.PatternLayout">
				<pattern>%syslogStart{USER}</pattern>
			</layout>
		</prefix>

		
		<encoder class="net.logstash.logback.encoder.LogstashEncoder" />
	</appender>

	<appender-ref ref="stash" />
</configuration>

**Comment by ssabnis** [comment] 2015-03-05 21:59
Ok I made it work, I can the logs in the syslog with syslog header, but there is one issue. I used markers to to use Ma(String, Object), when send map(string, int), it does get into JSON string when using socketAppender. Basically any integer object send to appendEntries() does not get seralized when sending to syslog. If change all that to Map(string,string) I se them generated into JSON log line. This not issue in File Appender. Only in SocketAppender,  Any clue?

**Comment by philsttr** [comment] 2015-03-10 04:01
Hi @ssabnis,

I am not able to reproduce the issue you are seeing with the Integer values in the map.

I tried the following code:

```java
        Map<String, Object> map = new HashMap<String, Object>();
        map.put("key1", 100);
        map.put("key2", "value2");
     
        LOGGER.warn(Markers.appendEntries(map), "Hello World");
```

With the following configuration:

```xml
    <conversionRule conversionWord="syslogStart" converterClass="ch.qos.logback.classic.pattern.SyslogStartConverter" />
    <appender name="tcp" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <remoteHost>localhost</remoteHost>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                <layout class="ch.qos.logback.classic.PatternLayout">
                    <pattern>%syslogStart{USER}</pattern>
                </layout>
            </prefix>            
        </encoder>
    </appender>
```

and received events like the following:

```
<12>Mar  9 20:56:50 xxx {"@timestamp":"2015-03-09T20:56:50.768-07:00","@version":1,"message":"Hello World","logger_name":"net.logstash.logback.TestIntegers","thread_name":"main","level":"WARN","level_value":30000,"HOSTNAME":"xxx","key2":"value2","key1":100}
```

**Comment by philsttr** [comment] 2015-03-10 04:02
For the server side, I just tested this with netcat, and watched the output.

```
nc -k -l 4560
```

**Comment by piefel** [comment] 2015-03-12 09:31
From the original bug description, it seems that `LogstashAccessTcpSocketAppender` was used instead of `LogstashTcpSocketAppender`.

**Comment by ssabnis** [comment] 2015-03-12 18:09
Following is my POM file


		
 		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.1.2</version>
		</dependency> 
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>1.1.2</version>
		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.2</version>
		</dependency>

And logback.xml file

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<conversionRule conversionWord="syslogStart"
		converterClass="ch.qos.logback.classic.pattern.SyslogStartConverter" />
	<appender name="stash"
		class="net.logstash.logback.appender.LogstashTcpSocketAppender">
		<remoteHost>host</remoteHost>
		<port>port</port>
		<encoder class="net.logstash.logback.encoder.LogstashEncoder">
			<prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
				<layout class="ch.qos.logback.classic.PatternLayout">
					<pattern>%syslogStart{USER}</pattern>
				</layout>
			</prefix>
			<timeZone>GMT</timeZone>
			<shortenedLoggerNameLength>0</shortenedLoggerNameLength>
		</encoder>
	</appender>
	<root level="all">
		<appender-ref ref="stash" />
	</root>
</configuration>

I am still encountering the same issue. Any clue?

**Comment by ssabnis** [comment] 2015-03-12 18:32
Aha! found out that it works in encoder version 3.6, there is bug in next releases. Thanks much for your help.

```xml
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>3.6</version>
		</dependency>
```

**Comment by philsttr** [comment] 2015-03-12 20:43
@ssabnis, Can you clarify the following....

When you say that "it works", are you referring to the "Integer values in the map" problem?

What problem are you still running into with the latest release (4.2)?

I have not been able to reproduce the  "Integer values in the map" problem.  It is working fine for me (see my [earlier comment](https://github.com/logstash/logstash-logback-encoder/issues/86#issuecomment-77992387)).

Can you provide:
* exactly what you are logging (your java code)
* exactly what the output is (captured to a file, or captured via netcat if using sockets)
* any errors you see

**Comment by ssabnis** [comment] 2015-03-12 23:37
Hi @philsttr 

yes the mapping of the int values in the map, I have used the 4.2 I had issue with that. When I switched to 3.6. I see it is working, I tried netcat unfortunately I do not see that in the netcat command. I will try again.

**Comment by philsttr** [comment] 2015-03-13 04:26
Sorry, I don't understand this:

{quote}
I tried netcat unfortunately I do not see that in the netcat command
{quote}

Do you see any output from nc?  You should definitely see something.  What output do you see?  Can you provide the output, along with what you are logging on the java side?

**Comment by ssabnis** [comment] 2015-03-13 06:16
Hi @philsttr 

I tried netcat I do not know for some reason I could not see any message coming in. The example with  logstash-logback-encoder 3.6  works fine, but the process hangs after that. For version 4.2, I do not see any messages coming into rsyslog with int values in the mapping.

Following is my console output
```code
23:00:59,422 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
23:00:59,422 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
23:00:59,423 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/sanjay.sabnis/Downloads/logbackexample/target/classes/logback.xml]
23:00:59,474 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
23:01:00,058 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word syslogStart with class [ch.qos.logback.classic.pattern.SyslogStartConverter]
23:01:00,058 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [net.logstash.logback.appender.LogstashTcpSocketAppender]
23:01:00,069 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stash]
23:01:00,232 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@11:70 - no applicable action for [prefix], current ElementPath  is [[configuration][appender][encoder][prefix]]
23:01:00,233 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@12:58 - no applicable action for [layout], current ElementPath  is [[configuration][appender][encoder][prefix][layout]]
23:01:00,233 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@13:15 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][prefix][layout][pattern]]
23:01:00,238 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ALL
23:01:00,238 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stash] to Logger[ROOT]
23:01:00,239 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
23:01:00,240 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@636a4985 - Registering current configuration as safe fallback
```

I am using Java 1.7.0_67

logback.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<conversionRule conversionWord="syslogStart"
		converterClass="ch.qos.logback.classic.pattern.SyslogStartConverter" />
	<appender name="stash"
		class="net.logstash.logback.appender.LogstashTcpSocketAppender">
		<remoteHost>host</remoteHost>
		<port>port</port>

		<encoder class="net.logstash.logback.encoder.LogstashEncoder">
			<prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
				<layout class="ch.qos.logback.classic.PatternLayout">
					<pattern>%syslogStart{USER}</pattern>
				</layout>
			</prefix>
			<timeZone>GMT</timeZone>
			<shortenedLoggerNameLength>0</shortenedLoggerNameLength>
		</encoder>
	</appender>

	<root level="all">
		<appender-ref ref="stash" />
	</root>
</configuration>
```
 
my pom.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.javacodegeeks.examples</groupId>
	<artifactId>logbackexample</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>logbackexample</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<!-- SLF4J - API -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.7</version>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>3.6</version>
		</dependency>
		<!-- logback -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.1.2</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-access</artifactId>
			<version>1.1.2</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>1.1.2</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
```

I tried it with simple example that I downloaded from here  http://a5e2fba00d8bcb729d89839f.javacodegeeks.netdna-cdn.com/wp-content/uploads/2014/07/logbackexample.zip

**Comment by philsttr** [comment] 2015-03-13 06:32
Can you provide the java code where you are logging the integer values?

For example, this is what I tested with:

```java
        Map<String, Object> map = new HashMap<String, Object>();
        map.put("key1", 100);
        map.put("key2", "value2");
     
        LOGGER.warn(Markers.appendEntries(map), "Hello World");
```

**Comment by ssabnis** [comment] 2015-03-13 13:30
Here is the code

```code
package com.javacodegeeks.examples.logbackexample;

import java.util.HashMap;
import java.util.Map;

import net.logstash.logback.marker.Markers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
	private static final Logger logger = LoggerFactory.getLogger(App.class);

	public static void main(String[] args) {

		long toolong = 80000;
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("key1", toolong);
		map.put("key2", "value2");

		logger.debug(Markers.appendEntries(map), "Hello World");

	}
}

```
in the above code,when I use 
```xml
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>3.6</version>
		</dependency>
```
I get the following output in rsyslog 

```code
2015-03-13T06:13:49.700295-07:00 172.20.66.675 {"@timestamp": "2015-03-13T13:13:50.012+00:00","@version":1,"message":"Hello World","logger_name":"c.j.e.l.App","thread_name":"main","level":"DEBUG","level_value":10000,"HOSTNAME":"My-Macbook.local","key2":"value2","key1":80000}
```
The java program hangs forever, and following is the console output in eclipse

```code
23:00:59,422 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
23:00:59,422 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
23:00:59,423 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/ssabnis/Downloads/logbackexample/target/classes/logback.xml]
23:00:59,474 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
23:01:00,058 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word syslogStart with class [ch.qos.logback.classic.pattern.SyslogStartConverter]
23:01:00,058 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [net.logstash.logback.appender.LogstashTcpSocketAppender]
23:01:00,069 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [stash]
23:01:00,232 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@11:70 - no applicable action for [prefix], current ElementPath  is [[configuration][appender][encoder][prefix]]
23:01:00,233 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@12:58 - no applicable action for [layout], current ElementPath  is [[configuration][appender][encoder][prefix][layout]]
23:01:00,233 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@13:15 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][prefix][layout][pattern]]
23:01:00,238 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ALL
23:01:00,238 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stash] to Logger[ROOT]
23:01:00,239 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
23:01:00,240 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@636a4985 - Registering current configuration as safe fallback
```

Now, If I switch to version 4.2

```xml
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>4.2</version>
		</dependency>
```

No console output, no syslog output, no errors, program does not hang. This is puzzling.

**Comment by philsttr** [comment] 2015-03-13 16:02
If that's all there is in your program, then I believe your program is just exiting before the sender thread gets a chance to send the message.

By default, the appender will allow the JVM to shutdown even if there are events still in the queue (see [here](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java#L72)).

You can change this behavior by doing the following:

Set the `daemon` field to false on the appender...

```xml
<daemon>false</false>
```

And [shutdown logback](http://logback.qos.ch/manual/configuration.html#stopContext) gracefully at the end of your main method.

```java
import org.sflf4j.LoggerFactory;
import ch.qos.logback.classic.LoggerContext;
...

// assuming SLF4J is bound to logback-classic in the current environment
LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
loggerContext.stop();
```

**Comment by ssabnis** [comment] 2015-03-13 18:13
Thanks @philsttr 

How do I gracefully shutdown the context, If put the shutdown at the end of the line, I still have the same problem as shutdown occurs before message being sent. What other options for the shutdown.

Thanks

**Comment by ssabnis** [comment] 2015-03-13 22:58
@philsttr 

I used the Thread.sleep(100) before shutting down the log context, now I see the integers in there. But it is still puzzling when I have all the custom fields as string, I never have to the shudown, sleep etc. It is happening when I have the integer values. It is worth taking a look.

**Comment by philsttr** [comment] 2015-03-14 06:42
If a clean shutdown is not performed (via `loggerContext.stop()`), then there is no guarantee that previously logged events are sent.  The only way to guarantee that all previously logged events are sent is to perform a clean shutdown.

There is nothing specific to integers that would cause a change in behavior.  If you're seeing differences, then it can just be attributed to timing differences.  To solve this you must use a clean shutdown.

If you still have problems using a clean shutdown with 4.2, then can you try using a clean shutdown with the latest from master (4.3-SNAPSHOT)?  There were some changes made to the shutdown logic that may affect the behavior you are seeing.  You'll have to checkout the code and build it yourself (`mvn clean install`)

Also, FYI, I'm not going to be available to debug this further for the next few days.

**Comment by ssabnis** [comment] 2015-03-14 17:23
Hi @philsttr ,

Thanks for the info, I got the 4.3-SNAPSHOT, I get this error src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java:[172,44] cannot find symbol
[ERROR] symbol  : method lineSeparator()

Any clue?

**Comment by philsttr** [comment] 2015-03-14 19:53
That method was added in Java 7. Use Java 7+

**Comment by philsttr** [comment] 2015-04-06 00:41
Hi @ssabnis,

When using a clean shutdown with the latest 4.3-SNAPSHOT, were all of the logged events received at the destination?

When I tried to repeat this, everything is working fine.  So I'll need to know how everything is working for you.

**Comment by philsttr** [comment] 2015-05-18 01:46
Closing this.  Please open a new issue for anything you encounter in v4.3

**Closed by philsttr** 2015-05-18 01:46 UTC
